name: "Snyk Code Scan"

on:
  push:
    branches:
      - master

jobs:
  pipeline-job:
    name: 'Snyk Code Scan'
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' 

      - name: Install Snyk
        run: |
          dotnet tool install -g snyk
          export PATH="$PATH:$HOME/.dotnet/tools"

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Snyk Code
        run: |
          snyk code test --sarif > results.sarif
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
