name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        dotnet-version: [8.0.x]
        os: [ubuntu-latest]

    steps:
      - name: Setup docker compose
        run: docker-compose -v
      - name: build docker image
        run: docker-compose build
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Tag and Push UserService
        run: |
          ls
          docker tag userservice:latest rboorsma/kwetter:userservice-latest
          docker push rboorsma/rboorsma:userservice-latest
    
